In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split

data=pd.read_csv(r"G:\Mi unidad\Universidad\Uni\Data science\Heavy Datasets\candy-data.csv")
data

,competitorname,chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,winpercent
0,100 Grand,1,0,1,0,0,1,0,1,0,0.732,0.860,66.971725
1,3 Musketeers,1,0,0,0,1,0,0,1,0,0.604,0.511,67.602936
2,One dime,0,0,0,0,0,0,0,0,0,0.011,0.116,32.261086
3,One quarter,0,0,0,0,0,0,0,0,0,0.011,0.511,46.116505
4,Air Heads,0,1,0,0,0,0,0,0,0,0.906,0.511,52.341465
...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Twizzlers,0,1,0,0,0,0,0,0,0,0.220,0.116,45.466282
81,Warheads,0,1,0,0,0,0,1,0,0,0.093,0.116,39.011898
82,WelchÕs Fruit Snacks,0,1,0,0,0,0,0,0,1,0.313,0.313,44.375519
83,WertherÕs Original Caramel,0,0,1,0,0,0,1,0,0,0.186,0.267,41.904308
84,Whoppers,1,0,0,0,0,1,0,0,1,0.872,0.848,49.524113

In [6]:
tic_tac_toe=pd.read_csv(r"G:\Mi unidad\Universidad\Uni\Data science\Heavy Datasets\tic-tac-toe.csv")
tic_tac_toe

,Top-Left,Top-Middle,Top-Right,Middle-Left,Middle-Middle,Middle-Right,Bottom-Left,Bottom-Middle,Bottom-Right,Class
0,x,x,x,x,o,o,x,o,o,positive
1,x,x,x,x,o,o,o,x,o,positive
2,x,x,x,x,o,o,o,o,x,positive
3,x,x,x,x,o,o,o,b,b,positive
4,x,x,x,x,o,o,b,o,b,positive
...,...,...,...,...,...,...,...,...,...,...
953,o,x,x,x,o,o,o,x,x,negative
954,o,x,o,x,x,o,x,o,x,negative
955,o,x,o,x,o,x,x,o,x,negative
956,o,x,o,o,x,x,x,o,x,negative
957,o,o,x,x,x,o,o,x,x,negative

In [7]:
# Create dummy variables using pandas
X = pd.get_dummies(tic_tac_toe.iloc[:,0:9])
y = tic_tac_toe.iloc[:, 9]

# Create temporary training and final testing datasets
X_temp, X_test, y_temp, y_test  =train_test_split(X, y, test_size=0.2, random_state=1111)

# Create the final training and validation datasets
X_train,X_val,y_train,y_val =train_test_split(X_temp, y_temp, test_size=0.25, random_state=1111)

ahora tengo:
* 60% training
* 20% validation
* 20% testing

### It is important to understand when you would use three datasets (training, validation, and testing) instead of two (training and testing). There is no point in creating an additional dataset split if you are not going to use it.
*  When testing parameters, tuning hyper-parameters, or anytime you are frequently evaluating model performance. Anytime we are evaluating model performance repeatedly we need to create training, validation, and testing datasets

# Clasification metrics
* Confusion Matrix
* Accuracy:Using the confusion matrix, we add the values that were predicted 0 and actually are 0 (which are called true negatives), to the values predicted to be 1 that are 1 (called true positives), and then divide by the total number of observations
* Precision: number of true positives out of all predicted positive values. 
* Recall: The recall metric is about finding all positive values.
* Specifity
* F1 Score

In [32]:
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=100, random_state=1111,max_depth=12)
rfc.fit(X_train,y_train)
print(rfc.feature_importances_)

[0.0179278  0.05479375 0.04768512 0.02308908 0.0337557  0.03828543
 0.01687254 0.04240096 0.04589067 0.02104176 0.03293429 0.03575388
 0.01515236 0.09435153 0.06989576 0.02453822 0.03733449 0.03089761
 0.01826101 0.0475916  0.04518754 0.02272203 0.03516563 0.04024076
 0.01803229 0.05101548 0.03918269]

In [23]:
# Create predictions
test_predictions = rfc.predict(X_test)

# Create and print the confusion matrix
cm = confusion_matrix(y_test,test_predictions)
print(cm)

# Print the true positives (actual 1s that were predicted 1s)
print("The number of true positives is: {}".format(cm[1,1]))

[[ 57   3]
 [  0 132]]
The number of true positives is: 132

In [21]:
from sklearn.metrics import precision_score,accuracy_score

test_predictions = rfc.predict(X_test)

# Create precision or recall score based on the metric you imported
score = precision_score(y_test,test_predictions,pos_label='positive')

# Print the final result
print("The precision value is {0:.2f}".format(score))
print("The accuracy value is {0:.2f}".format(accuracy_score(y_test,test_predictions)))

The precision value is 0.97
The accuracy value is 0.98

# Regression Metrics
* Mean absolute error:  It is the simplest and most intuitive error metric and is the average absolute difference between the predictions (y_i) and the actual values (y_i hat). If your dog had six puppies, but you had predicted only four, the absolute difference would be two. 
    * This metric treats all points equally and is not sensitive to outliers.
    * An example could be predicting your car's monthly gas bill, when an outlier may have been caused by a one-time road trip.
* Mean square error:
    * The MSE allows larger errors to have a larger impact on the model. 
    * Using the previous car example, if you knew once a year you might go on a road trip, you might expect to occasionally have a large error and would want your model to pick up on these trips.

Picking between the MAE and the MSE comes down to the application. These results are in different units though and should not be directly compared!

# The bias-variance trade-off
* Bias: Occurs when the model fails to find the relationships between the data and the response value. Bias leads to high errors on both the training and testing datasets and is associated with an underfit model.
    Underfitting (high bias) occurs when the model could not find the underlying patterns available in the data. This might happen if we don't have enough trees or the trees aren't deep enough
* Variance: Variance occurs when a model pays too close attention to the training data and fails to generalize to the testing data. These models perform well on only the training data, but not the testing data, and are considered to be overfit
    * Overfitting (high variance) occurs when our model starts to attach meaning to the noise in the training data.

In [33]:
test_scores, train_scores = [], []
for i in [1, 2, 3, 4, 5, 10, 20, 50]:
    rfc = RandomForestClassifier(n_estimators=i, random_state=1111)
    rfc.fit(X_train, y_train)
    # Create predictions for the X_train and X_test datasets.
    train_predictions = rfc.predict(X_train)
    test_predictions = rfc.predict(X_test)
    # Append the accuracy score for the test and train predictions.
    train_scores.append(round(accuracy_score(y_train, train_predictions), 2))
    test_scores.append(round(accuracy_score(y_test, test_predictions), 2))
# Print the train and test scores.
print("The training scores were: {}".format(train_scores))
print("The testing scores were: {}".format(test_scores))

The training scores were: [0.9, 0.88, 0.96, 0.97, 0.99, 1.0, 1.0, 1.0]
The testing scores were: [0.66, 0.64, 0.77, 0.81, 0.86, 0.92, 0.95, 0.98]

si:
    train > test: overfitting
    train ≈ test 
    train < test: underfitting